title: Nic Seymour-Smith
author: Nic Seymour-Smith

description: "Electronic hardware, digital interfaces, education and workshops"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: N. Seymour-Smith
  location: Brighton, UK
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nseymoursmith
  - title: linkedin
    url: http://www.linkedin.com/pub/nicolas-seymour-smith/35/617/432
  - title: github
    url: http://github.com/nseymoursmith
  - title: e-mail
    url: mailto:nseymoursmith@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Boiler Room Art Studios
  - line: Embassy Court
  - line: Brighton
  - line: BN1 2PX
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
